# Generated by Django 2.0.6 on 2018-08-27 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_url', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('data_text', models.CharField(max_length=50000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('exp_time', models.IntegerField(null=True)),
                ('data_title', models.CharField(max_length=500, null=True)),
                ('share_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('edit_p', models.CharField(max_length=50, null=True)),
                ('syntax', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='delinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_url', models.UUIDField(unique=True)),
                ('username_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sp_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('signed_in', models.CharField(default='no', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='addtodatabase',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastebin_app.user'),
        ),
    ]
