# Generated by Django 2.0.6 on 2018-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='editinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_text', models.CharField(max_length=50000)),
            ],
        ),
    ]
