# Generated by Django 2.0.6 on 2018-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0003_auto_20180827_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='editinfo',
            name='share_id2',
            field=models.UUIDField(null=True),
        ),
    ]
