# Generated by Django 2.0.6 on 2018-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0004_editinfo_share_id2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editinfo',
            name='share_id2',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
